name: build

on:
  push:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  pull_request:

env:
  IMAGE_NAME: steled/jdownloader

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          WITH_V: false
          RELEASE_BRANCHES: main
          INITIAL_VERSION: 0.1.0

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish arm64 images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: openjdk17-alpine.Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:openjdk17-alpine
            ${{ env.IMAGE_NAME }}:alpine
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.tag }}

      - name: Build and publish arm64 images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: openjdk17-ubuntu.Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:openjdk17-ubuntu
            ${{ env.IMAGE_NAME }}:openjdk17
            ${{ env.IMAGE_NAME }}:ubuntu
            ${{ env.IMAGE_NAME }}:latest 
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.tag }}
